version: "3.4"

services:
  task-manager:
    image: henriquemazzoleni/task-manager
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
